site_name: learning hub of the future

theme:
  name: material
  logo: "assets/logo.png"  # Agrega un logo personalizado
  favicon: "assets/favicon.png"  # Ícono del sitio
  features:
    - content.code.copy # Botón para copiar código
    - content.code.annotate # Permite anotaciones en el código
    - content.code.select # Agregar un selector de lenguajes
    - content.code.highlight # Resalta líneas específicas
  
    
  layout:
    width: full

extra_css:
  - stylesheets/extra.css
  - stylesheets/custom_htb.css
  - https://unpkg.com/katex@0/dist/katex.min.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js


plugins:
  - tags
  - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes:
         - custom-skip-class-name
       auto_caption: false
       caption_position: bottom
       background: white
       shadow: true
       manual: false

extra:
  annotate:
    json: [.s2]
  social:
    - icon: fontawesome/brands/mastodon 
      link: https://fosstodon.org/@squidfunk
    - icon: fontawesome/brands/github
      link: https://gihub.com/KEVIN-117
    - icon: fontawesome/brands/gitlab
      link: https://gihub.com/KEVIN-117
    - icon: fontawesome/brands/linkedin
      link: https://gihub.com/KEVIN-117
    - icon: fontawesome/brands/docker
      link: https://gihub.com/KEVIN-117
  generator: false

copyright: Copyright &copy; 2025 by K3V1N 117

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      pygments_lang_class: true
      linenums: false  # Si quieres numeración de líneas, cámbialo a true
      use_pygments: true
      pygments_style: dracula
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
